name: valkyrie
type: php
project_tld: local
docroot: web-test
php_version: "8.3"
webserver_type: apache-fpm
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: "2"
composer_root: ""
nodejs_version: "lts"  
web_environment: []
corepack_enable: false

